(()=>{const O='Berniocal',P='bernard',F='data/rozvrh.json',API=`https://api.github.com/repos/${O}/${P}/contents/${F}`,$=id=>document.getElementById(id);let sha=null,edit=null,dirty=false;
const tok=()=>localStorage.getItem('bernard_token')||'',heads=()=>({'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',...(tok()?{Authorization:'Bearer '+tok()}:{})}),b64d=s=>new TextDecoder().decode(Uint8Array.from(atob(s.replace(/\n/g,'')),c=>c.charCodeAt(0))),b64e=s=>{let a=new TextEncoder().encode(s),z='';for(let i=0;i<a.length;i+=8192)z+=String.fromCharCode(...a.subarray(i,i+8192));return btoa(z)},note=(t,c='')=>{let n=$('notice');n.textContent=t;n.className='notice show '+c},mark=v=>{dirty=v;$('saveGitHub').disabled=!v;$('dirty').textContent=v?'Neuložené změny':'Uloženo'};
async function connect(){let v=$('tokenInput').value.trim();if(v)localStorage.setItem('bernard_token',v);if(!tok()){note('Vlož GitHub token.','err');return}try{let r=await fetch(API,{headers:heads(),cache:'no-store'});if(!r.ok)throw Error((await r.json()).message||r.status);let j=await r.json();sha=j.sha;R.set(JSON.parse(b64d(j.content)));R.render();mark(false);$('tokenInput').value=tok();$('tokenState').textContent='GitHub připojen – token je uložen v tomto prohlížeči.';note('Data načtena přímo z GitHubu.','ok')}catch(e){note('GitHub: '+e.message,'err')}}
async function save(){if(!tok()){note('Nejdřív připoj token.','err');return}try{note('Ukládám…');if(!sha){let r=await fetch(API,{headers:heads()});let j=await r.json();sha=j.sha}let text=JSON.stringify(R.get(),null,2)+'\n',body={message:'Rozvrh: změny '+new Date().toLocaleDateString('cs-CZ'),content:b64e(text),sha,branch:'main'},r=await fetch(API,{method:'PUT',headers:{...heads(),'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw Error((await r.json()).message||r.status);sha=(await r.json()).content.sha;mark(false);note('Uloženo na GitHub.','ok')}catch(e){note('Uložení selhalo: '+e.message,'err');$('saveGitHub').disabled=false}}
function fill(e,m){edit={...m,kind:m.kind||e.kind||'lesson'};const duty=edit.kind==='duty';$('dlgTitle').textContent=duty?(m.id?'Upravit dohled':'Přidat dohled'):(m.type==='custom'?(m.id?'Upravit suplování':'Přidat hodinu'):'Upravit hodinu');$('fDate').value=m.date;$('fSubject').value=e.subject||(duty?'DOHLED':'');$('fClass').value=e.class||'';$('fRoom').value=e.room||'';$('fStart').value=e.start;$('fEnd').value=e.end;$('fNote').value=e.note||'';$('fStatus').value=e.status||'normal';$('del').classList.toggle('hidden',m.type==='base'&&!m.changed||m.type==='custom'&&!m.id);$('del').textContent=m.type==='base'?'Vrátit původní':'Smazat';$('dlg').showModal()}
function add(date,start,end,meta={}){const duty=meta.kind==='duty';fill({subject:duty?'DOHLED':'FYZ',class:'',room:'',start,end,note:duty?'':'Suplování',status:'normal',kind:duty?'duty':'lesson'},{type:'custom',date,id:null,changed:true,kind:duty?'duty':'lesson',period:meta.period||null})}
function absence(date){let c=R.change(date);$('aDate').value=date;$('aNote').value=c.absence?.note||'';$('adel').classList.toggle('hidden',!c.absence);$('adlg').showModal()}
$('saveLesson').onclick=()=>{let date=$('fDate').value,start=$('fStart').value,end=$('fEnd').value;if(!date||!start||!end||R.mins(end)<=R.mins(start)){alert('Zkontroluj datum a čas.');return}let e={subject:$('fSubject').value.trim(),class:$('fClass').value.trim(),room:$('fRoom').value.trim(),start,end,note:$('fNote').value.trim(),status:$('fStatus').value,kind:edit.kind||'lesson'};if(edit.type==='base'){let c=R.change(edit.date);c.events??={};c.events[edit.id]=e}else{let old=R.change(edit.date);old.custom??=[];if(edit.id){let i=old.custom.findIndex(x=>x.id===edit.id);if(edit.date===date&&i>=0)old.custom[i]={...e,id:edit.id};else{if(i>=0)old.custom.splice(i,1);R.cleanup(edit.date);let c=R.change(date);c.custom??=[];c.custom.push({...e,id:edit.id})}}else{let c=R.change(date);c.custom??=[];c.custom.push({...e,id:'c'+Date.now()})}}mark(true);$('dlg').close();R.render()};
$('del').onclick=()=>{let c=R.change(edit.date);if(edit.type==='base'){if(c.events)delete c.events[edit.id]}else c.custom=(c.custom||[]).filter(x=>x.id!==edit.id);R.cleanup(edit.date);mark(true);$('dlg').close();R.render()};
$('asave').onclick=()=>{R.change($('aDate').value).absence={note:$('aNote').value.trim()};mark(true);$('adlg').close();R.render()};$('adel').onclick=()=>{let k=$('aDate').value,c=R.change(k);delete c.absence;R.cleanup(k);mark(true);$('adlg').close();R.render()};
$('connect').onclick=connect;$('disconnect').onclick=()=>{localStorage.removeItem('bernard_token');$('tokenInput').value='';sha=null;$('tokenState').textContent='Token odpojen a zapomenut.';note('Token byl odstraněn z tohoto prohlížeče.','ok')};$('saveGitHub').onclick=save;$('addSub').onclick=()=>add(R.iso(R.week()),'08:00','08:45',{kind:'lesson',period:'1'});$('addAbs').onclick=()=>absence(R.iso(R.week()));window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
const saved=tok();if(saved)$('tokenInput').value=saved;
R.load({admin:true,edit:fill,add,absence}).then(()=>{if(tok()){$('tokenState').textContent='Uložený token nalezen – připojuji…';connect()}else $('tokenState').textContent='Bez tokenu můžeš připravit změny, ale neuložíš je na GitHub.'}).catch(e=>note('Načtení selhalo: '+e.message,'err'))})();
